In [1]:
import os
from pathlib import Path

parent_dir = Path().cwd().parent
os.chdir(parent_dir)

In [2]:
from src.data_pipeline.loader import DataPreparer
from src.data_pipeline.pipeline_models import data_pipeline_settings

In [3]:
loader = DataPreparer(data_pipeline_settings)

df = loader.load_pac()

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 189853 entries, 0 to 189852
Data columns (total 3 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   date               189853 non-null  datetime64[us]
 1   24-2000:Mg.Sulfur  189649 non-null  float64
 2   24-2000:D15        75455 non-null   float64
dtypes: datetime64[us](1), float64(2)
memory usage: 4.3 MB

In [7]:
df

                      date  24-2000:Mg.Sulfur  24-2000:D15
0      2023-01-01 00:00:00           6.572924          NaN
1      2023-01-01 00:10:00           6.730094          NaN
2      2023-01-01 00:20:00           7.158879          NaN
3      2023-01-01 00:30:00           7.620472          NaN
4      2023-01-01 00:40:00           8.173620          NaN
...                    ...                ...          ...
189848 2026-08-11 09:20:00                NaN     837.5121
189849 2026-08-11 09:30:00                NaN     837.4020
189850 2026-08-11 09:40:00                NaN     837.4866
189851 2026-08-11 09:50:00                NaN     837.4070
189852 2026-08-11 09:54:04                NaN     837.5897

[189853 rows x 3 columns]

In [ ]:
df[df["24-2000:Mg.Sulfur"].isna()]

                      date  24-2000:Mg.Sulfur  24-2000:D15
189649 2026-08-10 00:10:00                NaN     837.7360
189650 2026-08-10 00:20:00                NaN     837.6713
189651 2026-08-10 00:30:00                NaN     837.3017
189652 2026-08-10 00:40:00                NaN     837.1854
189653 2026-08-10 00:50:00                NaN     837.2652
...                    ...                ...          ...
189848 2026-08-11 09:20:00                NaN     837.5121
189849 2026-08-11 09:30:00                NaN     837.4020
189850 2026-08-11 09:40:00                NaN     837.4866
189851 2026-08-11 09:50:00                NaN     837.4070
189852 2026-08-11 09:54:04                NaN     837.5897

[204 rows x 3 columns]

In [12]:
df[df["24-2000:D15"].isna()]

                      date  24-2000:Mg.Sulfur  24-2000:D15
0      2023-01-01 00:00:00           6.572924          NaN
1      2023-01-01 00:10:00           6.730094          NaN
2      2023-01-01 00:20:00           7.158879          NaN
3      2023-01-01 00:30:00           7.620472          NaN
4      2023-01-01 00:40:00           8.173620          NaN
...                    ...                ...          ...
114393 2025-03-05 09:30:00           7.763748          NaN
114394 2025-03-05 09:40:00           7.438124          NaN
114395 2025-03-05 09:50:00           7.313701          NaN
114396 2025-03-05 10:00:00           7.059694          NaN
114397 2025-03-05 10:10:00           7.142857          NaN

[114398 rows x 3 columns]